include C:\masm32\include\Comctl32.inc
includelib C:\masm32\lib\Comctl32.lib

include C:\masm32\include\comdlg32.inc
includelib C:\masm32\lib\comdlg32.lib

include C:\masm32\include\gdi32.inc
includelib C:\masm32\lib\gdi32.lib

include C:\masm32\include\msvcrt.inc
includelib C:\masm32\lib\msvcrt.lib

include C:\masm32\include\masm32.inc
includelib C:\masm32\lib\masm32.lib

include C:\masm32\include\kernel32.inc
includelib C:\masm32\lib\kernel32.lib

include C:\masm32\include\shell32.inc
includelib C:\masm32\lib\shell32.lib

include C:\masm32\include\user32.inc
includelib C:\masm32\lib\user32.lib

include windows.inc
include GraphWin.inc


;INCLUDE C:\masm32\Irvine\Irvine32.inc
;INCLUDELIB C:\masm32\Irvine\Irvine32.lib



;includelib      C:\masm32\Irvine\Kernel32.lib
;includelib      C:\masm32\Irvine\User32.Lib